### ISSUE TITLE
Add Controller Doesn't Work

### ISSUE THREAD

**Issue by sidqiaverroes** [etrupja/complete-ecommerce-aspnet-mvc-application#8]
I followed the tutorial from Udemy while looking at the migration notes. After completing section 32 "Model Validation" and run the app, there is no error appear in the Visual Studio. I tried the add actor functionality, but nothing happened. How do I debug this error?

**Comment by JamesOmego** [comment]
Same problem here.

@sidqiaverroes Did you finally figure it out?

Any hints @etrupja

**Comment by dwarwick** [comment]
I am not the author, but I will try to help. Can you please post your Actor model code and the full form code?

I'm thinking that either your model properties do not have the Data Annotations or the form does not have the asp-for attributes properly setup, or they are missing from the form.

**Comment by JamesOmego** [comment]
Thanks @dwarwick 

These are my files:
[Models]
using System.ComponentModel.DataAnnotations;

namespace eTickets.Models
{
    public class Actor
    {
        [Key]
        public int Id { get; set; }

        [Display(Name ="Profile Picture")]
        [Required(ErrorMessage = "Profile Picture is Required")]
        public string ProfilePictureURL { get; set; }
        
        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Full Name is Required")]
        [StringLength(50,MinimumLength =3,ErrorMessage ="Full Name must be between 3 and 50 Characters")]
        public string FullName { get; set; }

        [Display(Name = "Biography")]
        [Required(ErrorMessage = "Biography is Required")]
        public string Bio { get; set; }

        //DB Relationship

        public List<Actor_Movie> Actors_Movies { get; set; }
    }
}
[Views]
[Create.cshtml]
@model Actor
@{
    ViewData["Title"] = "Add a new Actor";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add Actor</h1>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">

                <form asp-action="Create"method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" />

                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureURL" class="control-label"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" />
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success  float-right" style="margin-top: 15px"/>
                        <a class="btn btn-outline-secondary float-end" style="margin-top: 15px" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })

        $("#ProfilePictureURL").on("change",function(){
            var output= document.getElementById("ProfilePicturePreview");
            output.src=$(this).val();
        })
    </script>
}
[Index.cshtml]
@*Define model*@
@model IEnumerable<Actor>

@*Define ViewData*@

@{
    ViewData["Title"] ="List of Actors";

}
@*Program Code Starts Here -HTML*@
<div class="row"> 
    <div class=" col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.ProfilePictureURL)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>
                    @*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <th>Actions</th>
                    }*@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.ProfilePictureURL" alt="@item.FullName" style="max-width: 150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Bio)
                        </td>
                        @*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))*@
                        @*{*@
                            <td class="align-middle">
                                <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                                <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                                <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                            </td>
                        @*@}*@

                    </tr>
                }
            </tbody>

        </table>
    </div>

</div>

<div style="position: fixed; right: 25px; bottom:25px;"class="text-white">
    <a asp-controller="Actors" asp-action="Create" class="btn btn-success ">
        <i class="bi bi-plus-circle"></i> Add Actor</a>

</div>
[Controllers]

using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;

namespace eTickets.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;

        public ActorsController(IActorsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAll();
            return View(data);

        }
        //Get: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        //Post

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")]Actor actor)
        {
            if (!ModelState.IsValid)
            { 
                return View(actor);
            }
            _service.Add(actor);
            return RedirectToAction(nameof(Index));
        }
    }
}

**Comment by dwarwick** [comment]
From what I see, it looks like you have covered everything. If you set a
breakpoint in the controller, is the model state valid when everything is
filled out correctly, and invalid when it's not?

Sincerely,

David Warwick

**Comment by JamesOmego** [comment]
@dwarwick  ,
Thank you for your assistance.

I finally figured it out. It works just fine.

**Comment by dwarwick** [comment]
Sounds good. Glad you got it working.

Sincerely,

David Warwick
951-210-8209

**Comment by etrupja** [comment]
Thank you everyone!
